const express = require('express');
const prisma = require('../lib/prisma');

const router = express.Router();

const SELECT_FIELDS = {
  id: true,
  name: true,
  welcomeMessage: true,
  primaryColor: true,
  position: true,
  isActive: true,
  statusText: true,
  avatarIcon: true,
  avatarUrl: true,
  placeholderText: true,
  launcherText: true,
  theme: true,
  fontSize: true,
  borderRadius: true,
  starterPrompts: true,
  hideBranding: true,
};

// GET /widget/config/:botId
router.get('/config/:botId', async (req, res) => {
  try {
    let chatbot = await prisma.chatbot.findUnique({
      where: { id: req.params.botId },
      select: SELECT_FIELDS,
    });
    if (!chatbot) {
      chatbot = await prisma.chatbot.findFirst({
        where: { isActive: true },
        select: SELECT_FIELDS,
      });
    }
    if (!chatbot) {
      return res.json({
        id: req.params.botId || 'default',
        name: 'AI Support Chat',
        welcomeMessage: 'Hello! How can I help you today?',
        primaryColor: '#6366f1',
        position: 'bottom-right',
        isActive: true,
        statusText: 'Online',
        avatarIcon: 'bot',
        avatarUrl: '',
        placeholderText: 'Type a message...',
        launcherText: '',
        theme: 'light',
        fontSize: 'medium',
        borderRadius: '18px',
        starterPrompts: '',
        hideBranding: false,
      });
    }
    res.json(chatbot);
  } catch (error) {
    console.error('Widget config error:', error);
    res.json({
      id: req.params.botId || 'default',
      name: 'AI Support Chat',
      welcomeMessage: 'Hello! How can I help you today?',
      primaryColor: '#6366f1',
      position: 'bottom-right',
      isActive: true,
      statusText: 'Online',
      avatarIcon: 'bot',
      avatarUrl: '',
      placeholderText: 'Type a message...',
      launcherText: '',
      theme: 'light',
      fontSize: 'medium',
      borderRadius: '18px',
      starterPrompts: '',
      hideBranding: false,
    });
  }
});

// GET /widget/config
router.get('/config', async (req, res) => {
  try {
    const chatbot = await prisma.chatbot.findFirst({
      where: { isActive: true },
      select: SELECT_FIELDS,
    });
    if (!chatbot) {
      return res.json({
        id: 'default',
        name: 'AI Support Chat',
        welcomeMessage: 'Hello! How can I help you today?',
        primaryColor: '#6366f1',
        position: 'bottom-right',
        isActive: true,
        statusText: 'Online',
        avatarIcon: 'bot',
        avatarUrl: '',
        placeholderText: 'Type a message...',
        launcherText: '',
        theme: 'light',
        fontSize: 'medium',
        borderRadius: '18px',
        starterPrompts: '',
        hideBranding: false,
      });
    }
    res.json(chatbot);
  } catch (error) {
    console.error('Widget config error:', error);
    res.json({
      id: 'default',
      name: 'AI Support Chat',
      welcomeMessage: 'Hello! How can I help you today?',
      primaryColor: '#6366f1',
      position: 'bottom-right',
      isActive: true,
      statusText: 'Online',
      avatarIcon: 'bot',
      avatarUrl: '',
      placeholderText: 'Type a message...',
      launcherText: '',
      theme: 'light',
      fontSize: 'medium',
      borderRadius: '18px',
      starterPrompts: '',
      hideBranding: false,
    });
  }
});

// GET /widget/embed.js — Robust embed script
router.get('/embed.js', (req, res) => {
  const serverUrl = req.protocol + '://' + req.get('host');

  const lines = [
    '(function() {',
    "  'use strict';",
    '  if (window.__cbLoaded) return;',
    '  window.__cbLoaded = true;',
    '',
    '  var SRV = "' + serverUrl + '";',
    '  var scriptTag = document.currentScript;',
    '  if (!scriptTag) {',
    '    var scripts = document.getElementsByTagName("script");',
    '    for (var i = 0; i < scripts.length; i++) {',
    '      var src = scripts[i].src || "";',
    '      if (src.indexOf("/widget/embed.js") !== -1 || scripts[i].hasAttribute("data-chatbot-id") || scripts[i].hasAttribute("data-bot-id")) {',
    '        scriptTag = scripts[i];',
    '        break;',
    '      }',
    '    }',
    '  }',
    '  if (scriptTag && scriptTag.src) {',
    '    try { SRV = new URL(scriptTag.src, location.href).origin; } catch(e) {}',
    '  }',
    '  var botId = null;',
    '  if (scriptTag) {',
    '    botId = scriptTag.getAttribute("data-chatbot-id") || scriptTag.getAttribute("data-bot-id");',
    '    if (!botId && scriptTag.src && scriptTag.src.indexOf("?") !== -1) {',
    '      try {',
    '        var params = new URLSearchParams(scriptTag.src.split("?")[1]);',
    '        botId = params.get("botId") || params.get("id");',
    '      } catch(e) {}',
    '    }',
    '  }',
    '  var SK = "cb_sess_" + (botId || "def");',
    '  var sid = null;',
    '  try { sid = localStorage.getItem(SK); } catch(e) {}',
    '  if (!sid) {',
    '    sid = "sess_" + Math.random().toString(36).slice(2) + Date.now().toString(36);',
    '    try { localStorage.setItem(SK, sid); } catch(e) {}',
    '  }',
    '',
    '  var cfgUrl = botId ? SRV + "/widget/config/" + botId : SRV + "/widget/config";',
    '',
    '  function showPH() {',
    '    if (document.getElementById("cb-ph")) return;',
    '    var ph = document.createElement("button");',
    '    ph.id = "cb-ph";',
    '    ph.style.cssText = "position:fixed!important;bottom:20px!important;right:20px!important;width:58px!important;height:58px!important;border-radius:50%!important;background:#6366f1!important;border:none!important;cursor:pointer!important;z-index:2147483647!important;display:flex!important;align-items:center!important;justify-content:center!important;box-shadow:0 4px 20px rgba(0,0,0,.25)!important;pointer-events:auto!important;";',
    '    ph.innerHTML = \'<svg viewBox="0 0 24 24" style="width:26px;height:26px;fill:#fff"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z"/></svg>\';',
    '    (document.body || document.documentElement).appendChild(ph);',
    '  }',
    '  function rmPH() { var p = document.getElementById("cb-ph"); if (p) p.remove(); }',
    '',
    '  function boot() {',
    '    fetch(cfgUrl)',
    '      .then(function(r) { return r.json(); })',
    '      .then(function(cfg) { rmPH(); if (cfg) initWidget(cfg); })',
    '      .catch(function(e) {',
    '        console.warn("[ChatWidget] config fallback:", e);',
    '        rmPH();',
    '        initWidget({ name: "AI Support", welcomeMessage: "Hello! How can I help you?", primaryColor: "#6366f1", position: "bottom-right" });',
    '      });',
    '  }',
    '',
    '  function runOnReady() {',
    '    showPH();',
    '    boot();',
    '  }',
    '',
    '  if (document.readyState === "complete" || document.readyState === "interactive") {',
    '    runOnReady();',
    '  } else {',
    '    document.addEventListener("DOMContentLoaded", runOnReady);',
    '    window.addEventListener("load", runOnReady);',
    '  }',
    '',
    '  /* ===== WIDGET INIT ===== */',
    '  function initWidget(config) {',
    '    var pc      = config.primaryColor || "#6366f1";',
    '    var pos     = config.position || "bottom-right";',
    '    var posR    = pos.indexOf("right") >= 0 ? "20px" : "auto";',
    '    var posL    = pos.indexOf("left")  >= 0 ? "20px" : "auto";',
    '    var name    = config.name || "Chat";',
    '    var wMsg    = config.welcomeMessage || "Hello! How can I help you?";',
    '    var status  = config.statusText || "Online";',
    '    var avIcon  = config.avatarIcon || "bot";',
    '    var avUrl   = config.avatarUrl || "";',
    '    var holder  = config.placeholderText || "Type a message\u2026";',
    '    var lLabel  = config.launcherText || "";',
    '    var theme   = config.theme || "light";',
    '    var fontSz  = config.fontSize || "medium";',
    '    var rad     = config.borderRadius || "18px";',
    '    var prompts = (config.starterPrompts || "").split("\\n").map(function(s){return s.trim();}).filter(Boolean);',
    '    var noBrand = !!config.hideBranding;',
    '',
    '    /* Theme colors */',
    '    var isDark = theme === "dark";',
    '    var bgMain = isDark ? "#0f172a" : (theme === "indigo" ? "#ffffff" : (theme === "slate" ? "#f8fafc" : "#ffffff"));',
    '    var bgMsgs = isDark ? "#1e293b" : (theme === "indigo" ? "#f5f3ff" : (theme === "slate" ? "#e2e8f0" : "#f8fafc"));',
    '    var txtColor = isDark ? "#f8fafc" : "#1e293b";',
    '    var botBubBg = isDark ? "#334155" : "#ffffff";',
    '    var botBubTxt = isDark ? "#f8fafc" : "#1e293b";',
    '    var inpBg = isDark ? "#334155" : "#f3f4f8";',
    '    var inpBorder = isDark ? "#475569" : "#e5e7eb";',
    '    var fSize = fontSz === "small" ? "12.5px" : (fontSz === "large" ? "15px" : "13.5px");',
    '',
    '    /* Avatar HTML helper */',
    '    var initials = name.slice(0,2).toUpperCase();',
    '    function getAvHtml(szClass) {',
    '      if (avUrl) return \'<img src="\' + avUrl + \'" class="\' + szClass + \'" style="object-fit:cover;" alt="Avatar" />\';',
    '      if (avIcon === "sparkles") return \'<div class="\' + szClass + \'"><svg viewBox="0 0 24 24" style="width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:2"><path d="M12 3v3m0 12v3M3 12h3m12 0h3m-4.5-6.5l-2 2m-7 7l-2 2m11 0l-2-2m-7-7l-2-2"/></svg></div>\';',
    '      if (avIcon === "headset") return \'<div class="\' + szClass + \'"><svg viewBox="0 0 24 24" style="width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:2"><path d="M3 18v-6a9 9 0 0 1 18 0v6"/><path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z"/></svg></div>\';',
    '      if (avIcon === "user") return \'<div class="\' + szClass + \'"><svg viewBox="0 0 24 24" style="width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div>\';',
    '      return \'<div class="\' + szClass + \'">\' + initials + \'</div>\';',
    '    }',
    '',
    '    /* CSS */',
    '    var css = document.createElement("style");',
    '    css.textContent = [',
    '      ".cb-btn{position:fixed!important;bottom:20px!important;right:"+posR+"!important;left:"+posL+"!important;width:"+(lLabel ? "auto" : "58px")+"!important;height:58px!important;padding:"+(lLabel ? "0 22px" : "0")+"!important;border-radius:"+(lLabel ? "29px" : "50%")+"!important;background:"+pc+"!important;border:none!important;cursor:pointer!important;box-shadow:0 4px 20px rgba(0,0,0,.2)!important;z-index:2147483646!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:10px!important;color:#fff!important;font-weight:600!important;font-size:14px!important;transition:transform .3s,box-shadow .3s!important;pointer-events:auto!important;}",',
    '      ".cb-btn:hover{transform:scale(1.06)!important;box-shadow:0 6px 28px rgba(0,0,0,.28)!important;}",',
    '      ".cb-btn svg{width:26px;height:26px;fill:#fff;flex-shrink:0;}",',
    '      ".cb-box{position:fixed!important;bottom:90px!important;right:"+posR+"!important;left:"+posL+"!important;width:390px!important;max-width:calc(100vw - 30px)!important;height:560px!important;max-height:calc(100vh - 110px)!important;background:"+bgMain+"!important;border-radius:"+rad+"!important;box-shadow:0 14px 50px rgba(0,0,0,.2)!important;z-index:2147483645!important;display:none!important;flex-direction:column!important;overflow:hidden!important;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif!important;font-size:"+fSize+"!important;pointer-events:auto!important;border:1px solid rgba(0,0,0,.08);}",',
    '      ".cb-box.open{display:flex!important;animation:cb-up .28s cubic-bezier(.22,.68,0,1.2);}",',
    '      "@keyframes cb-up{from{opacity:0;transform:translateY(18px) scale(.97)}to{opacity:1;transform:translateY(0) scale(1)}}",',
    '      ".cb-hdr{background:"+pc+";color:#fff;padding:14px 18px;display:flex;align-items:center;justify-content:space-between;flex-shrink:0;}",',
    '      ".cb-hdr-left{display:flex;align-items:center;gap:10px;}",',
    '      ".cb-hdr-av{width:36px;height:36px;border-radius:50%;background:rgba(255,255,255,.25);display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;color:#fff;overflow:hidden;flex-shrink:0;}",',
    '      ".cb-hdr-name{font-size:14.5px;font-weight:700;line-height:1.2;color:#fff;}",',
    '      ".cb-hdr-status{font-size:11px;opacity:.9;display:flex;align-items:center;gap:5px;margin-top:2px;color:rgba(255,255,255,.9);}",',
    '      ".cb-hdr-dot{width:7px;height:7px;background:#4ade80;border-radius:50%;display:inline-block;box-shadow:0 0 6px #4ade80;}",',
    '      ".cb-hdr-x{background:none;border:none;color:#fff;cursor:pointer;font-size:24px;padding:0 3px;opacity:.8;line-height:1;}",',
    '      ".cb-hdr-x:hover{opacity:1;}",',
    '      ".cb-msgs{flex:1;overflow-y:auto;padding:16px 14px;display:flex;flex-direction:column;gap:12px;background:"+bgMsgs+";}",',
    '      ".cb-msgs::-webkit-scrollbar{width:4px;}.cb-msgs::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:4px;}",',
    '      ".cb-row{display:flex;align-items:flex-start;gap:8px;width:100%;animation:cb-up .2s ease;}",',
    '      ".cb-row.user{justify-content:flex-end;}",',
    '      ".cb-row.bot{justify-content:flex-start;}",',
    '      ".cb-av-sm{width:28px;height:28px;border-radius:50%;background:"+pc+";display:flex;align-items:center;justify-content:center;color:#fff;font-size:10px;font-weight:700;flex-shrink:0;margin-top:2px;overflow:hidden;}",',
    '      ".cb-bwrap{display:flex;flex-direction:column;max-width:80%;gap:4px;}",',
    '      ".cb-row.user .cb-bwrap{align-items:flex-end;}",',
    '      ".cb-row.bot  .cb-bwrap{align-items:flex-start;}",',
    '      ".cb-m{padding:10px 14px;border-radius:15px;line-height:1.55;word-wrap:break-word;white-space:pre-wrap;}",',
    '      ".cb-m.user{background:"+pc+";color:#fff;border-bottom-right-radius:4px;}",',
    '      ".cb-m.bot{background:"+botBubBg+";color:"+botBubTxt+";box-shadow:0 1px 4px rgba(0,0,0,.08);border:1px solid rgba(0,0,0,.06);border-bottom-left-radius:4px;}",',
    '      ".cb-prompts{display:flex;flex-wrap:wrap;gap:6px;margin-top:6px;}",',
    '      ".cb-chip{background:rgba(99,102,241,0.08);color:"+pc+";border:1px solid "+pc+"44;border-radius:16px;padding:6px 12px;font-size:12px;font-weight:500;cursor:pointer;transition:all .18s;text-align:left;}",',
    '      ".cb-chip:hover{background:"+pc+";color:#fff;transform:translateY(-1px);}",',
    '      ".cb-ts{font-size:10px;color:#94a3b8;padding:0 2px;}",',
    '      ".cb-typing{display:flex;align-items:center;gap:5px;padding:8px 12px;}",',
    '      ".cb-dot{width:7px;height:7px;background:#cbd5e1;border-radius:50%;animation:cb-bounce 1.4s infinite both;}",',
    '      ".cb-dot:nth-child(2){animation-delay:.2s;}.cb-dot:nth-child(3){animation-delay:.4s;}",',
    '      "@keyframes cb-bounce{0%,80%,100%{transform:scale(.6);opacity:.5}40%{transform:scale(1.1);opacity:1}}",',
    '      ".cb-inwrap{background:"+bgMain+";flex-shrink:0;padding:12px 14px;border-top:1px solid rgba(0,0,0,.06);position:relative;}",',
    '      ".cb-vwave{max-height:0;opacity:0;overflow:hidden;transition:all .28s cubic-bezier(.4,0,.2,1);display:flex;align-items:center;justify-content:space-between;background:linear-gradient(135deg, "+pc+"15, #ef444415);border-radius:12px;border:1px solid "+pc+"33;margin-bottom:0;padding:0 12px;}",',
    '      ".cb-vwave.on{max-height:50px;opacity:1;margin-bottom:8px;padding:8px 12px;}",',
    '      ".cb-vinfo{display:flex;align-items:center;gap:7px;color:#ef4444;font-size:12px;font-weight:600;}",',
    '      ".cb-vdot{width:8px;height:8px;background:#ef4444;border-radius:50%;animation:cb-vpulse 1.2s infinite;}",',
    '      "@keyframes cb-vpulse{0%,100%{transform:scale(1);opacity:1}50%{transform:scale(1.5);opacity:.5}}",',
    '      ".cb-vbars{display:flex;align-items:center;gap:3px;height:22px;}",',
    '      ".cb-vbar{width:3.5px;border-radius:3px;background:linear-gradient(to top, "+pc+", #ef4444);height:6px;transition:height .1s ease;animation:cb-wanim 0.7s infinite alternate ease-in-out;}",',
    '      ".cb-vbar:nth-child(1){animation-delay:0s;}.cb-vbar:nth-child(2){animation-delay:.1s;}.cb-vbar:nth-child(3){animation-delay:.2s;}.cb-vbar:nth-child(4){animation-delay:.3s;}.cb-vbar:nth-child(5){animation-delay:.4s;}.cb-vbar:nth-child(6){animation-delay:.5s;}.cb-vbar:nth-child(7){animation-delay:.6s;}",',
    '      "@keyframes cb-wanim{0%{height:4px;opacity:.5}100%{height:20px;opacity:1}}",',
    '      ".cb-vdone{display:flex;align-items:center;gap:4px;background:#ef4444;color:#fff;border:none;border-radius:14px;padding:4px 10px;font-size:11.5px;font-weight:600;cursor:pointer;transition:transform .15s,background .15s;}",',
    '      ".cb-vdone:hover{background:#dc2626;transform:scale(1.04);}",',
    '      ".cb-vdone svg{width:13px;height:13px;fill:currentColor;}",',
    '      ".cb-in{display:flex;align-items:center;gap:8px;background:"+inpBg+";border-radius:24px;border:1.5px solid "+inpBorder+";padding:6px 6px 6px 14px;transition:border-color .2s,box-shadow .2s;}",',
    '      ".cb-inwrap:focus-within .cb-in{border-color:"+pc+";box-shadow:0 0 0 3px "+pc+"22;}",',
    '      ".cb-inp-wrap{flex:1;overflow:hidden;}",',
    '      ".cb-inp{width:100%;border:none;background:transparent;color:"+txtColor+";outline:none;font-family:inherit;font-size:inherit;resize:none;max-height:100px;line-height:1.5;padding:4px 0;}",',
    '      ".cb-snd{background:"+pc+";border:none;border-radius:50%;width:34px;height:34px;min-width:34px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:transform .18s;flex-shrink:0;}",',
    '      ".cb-snd:hover{transform:scale(1.08);}",',
    '      ".cb-snd:disabled{opacity:.4;cursor:not-allowed;transform:none;}",',
    '      ".cb-snd svg{width:15px;height:15px;fill:#fff;}",',
    '      ".cb-mic{background:none;border:none;cursor:pointer;padding:6px;border-radius:50%;display:flex;align-items:center;justify-content:center;color:#94a3b8;transition:all .2s;flex-shrink:0;position:relative;}",',
    '      ".cb-mic:hover{color:"+pc+";background:rgba(99,102,241,0.1);}",',
    '      ".cb-mic.rec{color:#ef4444;background:rgba(239,68,68,0.12);animation:cb-mring 1.5s infinite;}",',
    '      "@keyframes cb-mring{0%{box-shadow:0 0 0 0 rgba(239,68,68,.4)}70%{box-shadow:0 0 0 10px rgba(239,68,68,0)}100%{box-shadow:0 0 0 0 rgba(239,68,68,0)}}",',
    '      ".cb-mic svg{width:19px;height:19px;fill:currentColor;}",',
    '      ".cb-ftr{text-align:center;padding:4px 0 2px;font-size:10.5px;color:#94a3b8;background:"+bgMain+";}",',
    '      ".cb-ftr a{color:"+pc+";text-decoration:none;font-weight:600;}",',
    '      "@media(max-width:480px){.cb-box{width:calc(100vw - 16px)!important;right:8px!important;left:8px!important;bottom:76px!important;}.cb-btn{bottom:14px!important;}}"',
    '    ].join("");',
    '    document.head.appendChild(css);',
    '',
    '    /* Launcher button */',
    '    var btn = document.createElement("button");',
    '    btn.id = "cb-launcher";',
    '    btn.className = "cb-btn";',
    '    btn.setAttribute("aria-label","Open chat");',
    '    btn.innerHTML = \'<svg viewBox="0 0 24 24"><path d="M20 2H4c-1.1 0-2 .9-2 2v18l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H6l-2 2V4h16v12z"/></svg>\' + (lLabel ? \'<span>\' + lLabel + \'</span>\' : \'\');',
    '    (document.body || document.documentElement).appendChild(btn);',
    '',
    '    /* Widget box */',
    '    var box = document.createElement("div");',
    '    box.className = "cb-box";',
    '    box.innerHTML =',
    '      \'<div class="cb-hdr">\' +',
    '        \'<div class="cb-hdr-left">\' +',
    '          getAvHtml("cb-hdr-av") +',
    '          \'<div class="cb-hdr-info">\' +',
    '            \'<div class="cb-hdr-name">\' + name + \'</div>\' +',
    '            \'<div class="cb-hdr-status"><span class="cb-hdr-dot"></span>\' + status + \'</div>\' +',
    '          \'</div>\' +',
    '        \'</div>\' +',
    '        \'<button class="cb-hdr-x" aria-label="Close">&times;</button>\' +',
    '      \'</div>\' +',
    '      \'<div class="cb-msgs"></div>\' +',
    '      \'<div class="cb-inwrap">\' +',
    '        \'<div class="cb-vwave">\' +',
    '          \'<div class="cb-vinfo"><span class="cb-vdot"></span>Listening...</div>\' +',
    '          \'<div class="cb-vbars">\' +',
    '            \'<div class="cb-vbar"></div><div class="cb-vbar"></div><div class="cb-vbar"></div><div class="cb-vbar"></div><div class="cb-vbar"></div><div class="cb-vbar"></div><div class="cb-vbar"></div>\' +',
    '          \'</div>\' +',
    '          \'<button class="cb-vdone"><svg viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg> Done</button>\' +',
    '        \'</div>\' +',
    '        \'<div class="cb-in">\' +',
    '          \'<div class="cb-inp-wrap"><textarea class="cb-inp" rows="1" placeholder="\' + holder + \'"></textarea></div>\' +',
    '          \'<button class="cb-mic" title="Voice input"><svg viewBox="0 0 24 24"><path d="M12 14c1.66 0 3-1.34 3-3V5c0-1.66-1.34-3-3-3S9 3.34 9 5v6c0 1.66 1.34 3 3 3zm5.3-3c0 3-2.54 5.1-5.3 5.1S6.7 14 6.7 11H5c0 3.41 2.72 6.23 6 6.72V21h2v-3.28c3.28-.48 6-3.3 6-6.72h-1.7z"/></svg></button>\' +',
    '          \'<button class="cb-snd"><svg viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg></button>\' +',
    '        \'</div>\' +',
    '      \'</div>\' +',
    '      (noBrand ? \'\' : \'<div class="cb-ftr">Powered by <a href="#" target="_blank">AI Chatbot</a></div>\');',
    '    (document.body || document.documentElement).appendChild(box);',
    '',
    '    var msgs    = box.querySelector(".cb-msgs");',
    '    var inp     = box.querySelector(".cb-inp");',
    '    var sndBtn  = box.querySelector(".cb-snd");',
    '    var clsBtn  = box.querySelector(".cb-hdr-x");',
    '    var micBtn  = box.querySelector(".cb-mic");',
    '    var vwave   = box.querySelector(".cb-vwave");',
    '    var vdoneBtn= box.querySelector(".cb-vdone");',
    '    var isOpen = false, isSending = false;',
    '',
    '    /* Auto-resize textarea */',
    '    inp.addEventListener("input", function() {',
    '      inp.style.height = "auto";',
    '      inp.style.height = Math.min(inp.scrollHeight, 100) + "px";',
    '    });',
    '',
    '    /* ---- Voice Input ---- */',
    '    var vRecording = false, vManualStop = false, activeRec = null, recRestartTimer = null;',
    '    var audioCtx = null, analyser = null, animFrame = null, mediaStream = null;',
    '    var baseText = "";',
    '',
    '    function updateAudioLevel() {',
    '      if (!vRecording || !analyser) return;',
    '      var data = new Uint8Array(analyser.frequencyBinCount);',
    '      analyser.getByteFrequencyData(data);',
    '      var sum = 0;',
    '      for (var i = 0; i < data.length; i++) sum += data[i];',
    '      var avg = sum / data.length;',
    '      var bars = vwave.querySelectorAll(".cb-vbar");',
    '      for (var b = 0; b < bars.length; b++) {',
    '        var h = Math.min(22, Math.max(4, (avg / 128) * (12 + b * 2)));',
    '        bars[b].style.height = h + "px";',
    '      }',
    '      animFrame = requestAnimationFrame(updateAudioLevel);',
    '    }',
    '',
    '    if ("SpeechRecognition" in window || "webkitSpeechRecognition" in window) {',
    '      var SRAPI = window.SpeechRecognition || window.webkitSpeechRecognition;',
    '      function createRecInstance() {',
    '        var r = new SRAPI();',
    '        r.continuous = true;',
    '        r.interimResults = true;',
    '        r.lang = "en-US";',
    '        r.onstart = function() {',
    '          vRecording = true;',
    '          micBtn.classList.add("rec");',
    '          vwave.classList.add("on");',
    '          inp.focus();',
    '        };',
    '        r.onresult = function(ev) {',
    '          var finalT = "", interimT = "";',
    '          for (var i = 0; i < ev.results.length; i++) {',
    '            if (ev.results[i].isFinal) {',
    '              finalT += ev.results[i][0].transcript + " ";',
    '            } else {',
    '              interimT += ev.results[i][0].transcript;',
    '            }',
    '          }',
    '          var fullText = (baseText + " " + finalT + interimT).replace(/\\s+/g, " ").trim();',
    '          inp.value = fullText;',
    '          inp.style.height = "auto";',
    '          inp.style.height = Math.min(inp.scrollHeight, 100) + "px";',
    '          inp.scrollTop = inp.scrollHeight;',
    '        };',
    '        r.onerror = function(ev) {',
    '          if (ev.error === "aborted" || ev.error === "no-speech") return;',
    '          if (ev.error === "not-allowed" || ev.error === "service-not-allowed") {',
    '            alert("Microphone permission was denied. Please allow microphone access in your browser.");',
    '            stopVoice();',
    '          }',
    '        };',
    '        r.onend = function() {',
    '          activeRec = null;',
    '          if (vRecording && !vManualStop) {',
    '            clearTimeout(recRestartTimer);',
    '            recRestartTimer = setTimeout(function() {',
    '              if (vRecording && !vManualStop) {',
    '                try {',
    '                  activeRec = createRecInstance();',
    '                  activeRec.start();',
    '                } catch(e) { stopVoice(); }',
    '              }',
    '            }, 100);',
    '          } else {',
    '            stopVoice();',
    '          }',
    '        };',
    '        return r;',
    '      }',
    '      function startVoice() {',
    '        if (vRecording) return;',
    '        vManualStop = false;',
    '        vRecording = true;',
    '        baseText = inp.value.trim();',
    '        micBtn.classList.add("rec");',
    '        vwave.classList.add("on");',
    '        inp.focus();',
    '        try {',
    '          activeRec = createRecInstance();',
    '          activeRec.start();',
    '        } catch(e) { stopVoice(); }',
    '        if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {',
    '          navigator.mediaDevices.getUserMedia({ audio: true }).then(function(stream) {',
    '            mediaStream = stream;',
    '            var AudioContextClass = window.AudioContext || window.webkitAudioContext;',
    '            if (AudioContextClass) {',
    '              audioCtx = new AudioContextClass();',
    '              var source = audioCtx.createMediaStreamSource(stream);',
    '              analyser = audioCtx.createAnalyser();',
    '              analyser.fftSize = 32;',
    '              source.connect(analyser);',
    '              updateAudioLevel();',
    '            }',
    '          }).catch(function(){});',
    '        }',
    '      }',
    '      function stopVoice() {',
    '        vManualStop = true;',
    '        vRecording = false;',
    '        clearTimeout(recRestartTimer);',
    '        if (animFrame) cancelAnimationFrame(animFrame);',
    '        if (mediaStream) {',
    '          mediaStream.getTracks().forEach(function(t) { t.stop(); });',
    '          mediaStream = null;',
    '        }',
    '        if (audioCtx) {',
    '          try { audioCtx.close(); } catch(e){}',
    '          audioCtx = null;',
    '        }',
    '        analyser = null;',
    '        micBtn.classList.remove("rec");',
    '        vwave.classList.remove("on");',
    '        if (activeRec) {',
    '          try { activeRec.stop(); } catch(e) {}',
    '          activeRec = null;',
    '        }',
    '        inp.focus();',
    '      }',
    '      micBtn.onclick = function() { vRecording ? stopVoice() : startVoice(); };',
    '      vdoneBtn.onclick = stopVoice;',
    '    } else {',
    '      micBtn.style.display = "none";',
    '    }',
    '',
    '    /* ---- Helpers ---- */',
    '    function nowTime() {',
    '      var d=new Date(), h=d.getHours(), m=d.getMinutes();',
    '      return (h%12||12)+":"+(m<10?"0"+m:m)+" "+(h>=12?"PM":"AM");',
    '    }',
    '    function botAv() {',
    '      var el = document.createElement("div");',
    '      el.className = "cb-av-sm";',
    '      el.innerHTML = getAvHtml("cb-av-sm");',
    '      return el;',
    '    }',
    '    function addMsg(text, role) {',
    '      var row  = document.createElement("div"); row.className = "cb-row " + role;',
    '      var wrap = document.createElement("div"); wrap.className = "cb-bwrap";',
    '      var bub  = document.createElement("div"); bub.className  = "cb-m " + role; bub.textContent = text;',
    '      var ts   = document.createElement("span"); ts.className = "cb-ts"; ts.textContent = nowTime();',
    '      wrap.appendChild(bub); wrap.appendChild(ts);',
    '      if (role === "bot") { row.appendChild(botAv()); row.appendChild(wrap); }',
    '      else { row.appendChild(wrap); }',
    '      msgs.appendChild(row); msgs.scrollTop = msgs.scrollHeight;',
    '      return bub;',
    '    }',
    '',
    '    /* Welcome message */',
    '    addMsg(wMsg, "bot");',
    '',
    '    /* Render Starter Prompt Chips */',
    '    if (prompts.length > 0) {',
    '      var pContainer = document.createElement("div");',
    '      pContainer.className = "cb-prompts";',
    '      prompts.forEach(function(promptText) {',
    '        var chip = document.createElement("button");',
    '        chip.className = "cb-chip";',
    '        chip.textContent = promptText;',
    '        chip.onclick = function() {',
    '          inp.value = promptText;',
    '          sendMsg();',
    '        };',
    '        pContainer.appendChild(chip);',
    '      });',
    '      msgs.appendChild(pContainer);',
    '    }',
    '',
    '    /* ---- Send message ---- */',
    '    function sendMsg() {',
    '      var text = inp.value.trim();',
    '      if (!text || isSending) return;',
    '      if (vRecording) stopVoice();',
    '',
    '      /* user bubble */',
    '      var urow = document.createElement("div"); urow.className = "cb-row user";',
    '      var uwrap = document.createElement("div"); uwrap.className = "cb-bwrap";',
    '      var ubub  = document.createElement("div"); ubub.className = "cb-m user"; ubub.textContent = text;',
    '      var uts   = document.createElement("span"); uts.className = "cb-ts"; uts.textContent = nowTime();',
    '      uwrap.appendChild(ubub); uwrap.appendChild(uts); urow.appendChild(uwrap);',
    '      msgs.appendChild(urow); msgs.scrollTop = msgs.scrollHeight;',
    '',
    '      inp.value = ""; inp.style.height = "auto";',
    '      isSending = true; sndBtn.disabled = true;',
    '',
    '      /* bot bubble with typing dots */',
    '      var brow  = document.createElement("div"); brow.className = "cb-row bot";',
    '      var bwrap = document.createElement("div"); bwrap.className = "cb-bwrap";',
    '      var bbub  = document.createElement("div"); bbub.className = "cb-m bot";',
    '      bbub.innerHTML = \'<div class="cb-typing"><div class="cb-dot"></div><div class="cb-dot"></div><div class="cb-dot"></div></div>\';',
    '      var bts   = document.createElement("span"); bts.className = "cb-ts";',
    '      bwrap.appendChild(bbub); bwrap.appendChild(bts);',
    '      brow.appendChild(botAv()); brow.appendChild(bwrap);',
    '      msgs.appendChild(brow); msgs.scrollTop = msgs.scrollHeight;',
    '',
    '      var firstToken = true;',
    '',
    '      fetch(SRV + "/api/chat/stream", {',
    '        method: "POST",',
    '        headers: { "Content-Type": "application/json" },',
    '        body: JSON.stringify({ message:text, sessionId:sid, botId:config.id, pageUrl:location.href })',
    '      })',
    '      .then(function(response) {',
    '        var reader  = response.body.getReader();',
    '        var decoder = new TextDecoder();',
    '        var buf     = "";',
    '',
    '        function pump() {',
    '          reader.read().then(function(chunk) {',
    '            if (chunk.done) {',
    '              bts.textContent = nowTime();',
    '              isSending = false; sndBtn.disabled = false;',
    '              return;',
    '            }',
    '            buf += decoder.decode(chunk.value, { stream: true });',
    '            var parts = buf.split("\\n");',
    '            buf = parts.pop() || "";',
    '            for (var i = 0; i < parts.length; i++) {',
    '              var line = parts[i].trim();',
    '              if (!line || line.indexOf("data: ") !== 0) continue;',
    '              try {',
    '                var d = JSON.parse(line.slice(6));',
    '                if (d.type === "chunk") {',
    '                  if (firstToken) { bbub.innerHTML = ""; firstToken = false; }',
    '                  bbub.textContent += d.content;',
    '                  msgs.scrollTop = msgs.scrollHeight;',
    '                } else if (d.type === "start" && d.sessionId) {',
    '                  sid = d.sessionId;',
    '                  try { localStorage.setItem(SK, sid); } catch(e) {}',
    '                } else if (d.type === "done") {',
    '                  bts.textContent = nowTime();',
    '                } else if (d.type === "error") {',
    '                  if (firstToken) bbub.innerHTML = "";',
    '                  bbub.textContent = "Sorry, something went wrong.";',
    '                }',
    '              } catch(e) {}',
    '            }',
    '            pump();',
    '          }).catch(function() {',
    '            if (firstToken) bbub.innerHTML = "";',
    '            if (!bbub.textContent) bbub.textContent = "Connection error. Please try again.";',
    '            bts.textContent = nowTime();',
    '            isSending = false; sndBtn.disabled = false;',
    '          });',
    '        }',
    '        pump();',
    '      })',
    '      .catch(function() {',
    '        if (firstToken) bbub.innerHTML = "";',
    '        bbub.textContent = "Connection error. Please try again.";',
    '        bts.textContent = nowTime();',
    '        isSending = false; sndBtn.disabled = false;',
    '      });',
    '    }',
    '',
    '    /* Controls */',
    '    btn.onclick = function() {',
    '      isOpen = !isOpen;',
    '      box.classList.toggle("open", isOpen);',
    '      if (isOpen) inp.focus();',
    '    };',
    '    clsBtn.onclick = function() { isOpen = false; box.classList.remove("open"); };',
    '    sndBtn.onclick = sendMsg;',
    '    inp.addEventListener("keydown", function(e) {',
    '      if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMsg(); }',
    '    });',
    '',
    '  } /* end initWidget */',
    '',
    '})();',
  ];

  const script = lines.join('\n');

  res.setHeader('Content-Type', 'application/javascript');
  res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0');
  res.setHeader('Pragma', 'no-cache');
  res.send(script);
});

module.exports = router;
