-- AlterTable
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "statusText" TEXT NOT NULL DEFAULT 'Online';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "avatarIcon" TEXT NOT NULL DEFAULT 'bot';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "placeholderText" TEXT NOT NULL DEFAULT 'Type a message...';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "launcherText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "theme" TEXT NOT NULL DEFAULT 'light';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "fontSize" TEXT NOT NULL DEFAULT 'medium';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "borderRadius" TEXT NOT NULL DEFAULT '18px';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "starterPrompts" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Chatbot" ADD COLUMN IF NOT EXISTS "hideBranding" BOOLEAN NOT NULL DEFAULT false;
